#### register user
POST http://{{host}}:{{port}}/api/user/register
Content-Type: application/json

{
	"username": "test",
	"age": 101,
	"score": 1000,
	"password": "password1"
}

#### login user
POST http://{{host}}:{{port}}/api/user/login
Content-Type: application/json

{
	"username": "test",
	"password": "testtest"
}

#### get user details
GET http://{{host}}:{{port}}/api/user/details
sessionToken: 6c800406-d434-4551-858b-02b1b4c83213